version: '3'
services:
  app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork: