version: '3'
services:
  backend:
    build:
      context: ../
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ../FE/
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork: